### ISSUE TITLE
null pointer deference when Fauceting tokens

### ISSUE THREAD

**Issue by boddumanohar** [0chain/zwalletcli#186]
Command:
`zwallet faucet --methodName "pour" --input "{}" --tokens 600`

```
0chain-core-sdk [DEBUG]  2022/10/10 15:30:55.354137 transaction_base.go:604: Confirmation round: 410468
0chain-core-sdk [INFO]   2022/10/10 15:30:55.354275 transaction_base.go:439: Query from https://load.devnet-0chain.net/sharder01/v1/block/get?round=410469&content=header
0chain-core-sdk [INFO]   2022/10/10 15:30:55.354354 transaction_base.go:439: Query from https://load.devnet-0chain.net/sharder02/v1/block/get?round=410469&content=header
0chain-core-sdk [DEBUG]  2022/10/10 15:30:55.410287 transaction_base.go:555: https://load.devnet-0chain.net/sharder01/v1/block/get?round=410469&content=header200 OK
0chain-core-sdk [DEBUG]  2022/10/10 15:30:55.410759 transaction_base.go:555: https://load.devnet-0chain.net/sharder02/v1/block/get?round=410469&content=header200 OK
0chain-core-sdk [INFO]   2022/10/10 15:30:55.410974 transaction_base.go:439: Query from https://load.devnet-0chain.net/sharder02/v1/block/get?round=410470&content=header
0chain-core-sdk [INFO]   2022/10/10 15:30:55.410979 transaction_base.go:439: Query from https://load.devnet-0chain.net/sharder01/v1/block/get?round=410470&content=header
0chain-core-sdk [DEBUG]  2022/10/10 15:30:55.464238 transaction_base.go:555: https://load.devnet-0chain.net/sharder02/v1/block/get?round=410470&content=header400 Bad Request
0chain-core-sdk [ERROR]  2022/10/10 15:30:55.464379 transaction_base.go:585: {"code":"invalid_request","error":"invalid_request: Invalid request (Block not available)"}

0chain-core-sdk [DEBUG]  2022/10/10 15:30:55.464403 transaction_base.go:555: https://load.devnet-0chain.net/sharder01/v1/block/get?round=410470&content=header400 Bad Request
0chain-core-sdk [ERROR]  2022/10/10 15:30:55.464418 transaction_base.go:585: {"code":"invalid_request","error":"invalid_request: Invalid request (Block not available)"}

0chain-core-sdk [INFO]   2022/10/10 15:30:55.464437 wallet_base.go:231: Minimum sharders used for verify :1
0chain-core-sdk [INFO]   2022/10/10 15:30:55.464461 transaction_base.go:610: round info not found. after a second falling thru to 1of 2Sharders
0chain-core-sdk [INFO]   2022/10/10 15:30:56.465508 wallet_base.go:231: Minimum sharders used for verify :1
0chain-core-sdk [INFO]   2022/10/10 15:30:56.465837 transaction_base.go:439: Query from https://load.devnet-0chain.net/sharder01/v1/block/get?round=410470&content=header
0chain-core-sdk [INFO]   2022/10/10 15:30:56.465921 transaction_base.go:439: Query from https://load.devnet-0chain.net/sharder02/v1/block/get?round=410470&content=header
0chain-core-sdk [DEBUG]  2022/10/10 15:30:56.552363 transaction_base.go:555: https://load.devnet-0chain.net/sharder02/v1/block/get?round=410470&content=header200 OK
0chain-core-sdk [DEBUG]  2022/10/10 15:30:56.581607 transaction_base.go:555: https://load.devnet-0chain.net/sharder01/v1/block/get?round=410470&content=header200 OK
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x101417dd8]

goroutine 47 [running]:
github.com/0chain/gosdk/zcncore.(*Transaction).GetVerifyError(...)
	/Users/manohar/go/pkg/mod/github.com/0chain/gosdk@v1.8.9-0.20220929114139-e7247ba20041/zcncore/transaction_base.go:662
github.com/0chain/zwalletcli/cmd.(*ZCNStatus).OnVerifyComplete(0x140003ebe30?, 0x140003c2ec0?, 0x14000386a80?)
	/Users/manohar/0chain/zwalletcli/cmd/common.go:76 +0x78
github.com/0chain/gosdk/zcncore.(*Transaction).completeVerifyWithConStatus(0x140001bac80?, 0x14000386000?, 0xa57?, {0x14000386a80?, 0x14000490058?}, {0x0?, 0x0?})
	/Users/manohar/go/pkg/mod/github.com/0chain/gosdk@v1.8.9-0.20220929114139-e7247ba20041/zcncore/transaction_base.go:222 +0xc0
github.com/0chain/gosdk/zcncore.(*Transaction).completeVerify(...)
	/Users/manohar/go/pkg/mod/github.com/0chain/gosdk@v1.8.9-0.20220929114139-e7247ba20041/zcncore/transaction_base.go:210
github.com/0chain/gosdk/zcncore.(*Transaction).Verify.func1()
	/Users/manohar/go/pkg/mod/github.com/0chain/gosdk@v1.8.9-0.20220929114139-e7247ba20041/zcncore/transaction.go:965 +0x5ac
created by github.com/0chain/gosdk/zcncore.(*Transaction).Verify
	/Users/manohar/go/pkg/mod/github.com/0chain/gosdk@v1.8.9-0.20220929114139-e7247ba20041/zcncore/transaction.go:895 +0x298
```

happens with the latest go-sdk version

**Comment by iamrz1** [comment]
Couldn't reproduce the issue.
cc @dabasov @boddumanohar

**Comment by boddumanohar** [comment]
Hi @iamrz1, Thanks for checking this. 

the error seems to be coming from here:

https://github.com/0chain/gosdk/blob/85a1b96edabcf9ba31cc5be9e45ef134728cd349/zcncore/transaction_base.go#L661-L662

But I am lately not seeing this error. Will re-open this if I see the issue.
