### ISSUE TITLE
panic when tring to recover wallet from mnemonics

### ISSUE THREAD

**Issue by boddumanohar** [0chain/zwalletcli#259]
```
zwallet recoverwallet --mnemonic "border laptop library theory pave brain decline jeans winner frame throw gadget amused mule farm labor torch slight pride lottery cash youth ocean route"
```

output

```
0chain-core-sdk [INFO]   2023/05/26 10:19:46.628744 wallet_base.go:310: ******* Wallet SDK Version:v1.8.13-45-g29b9769 ******* (SetLogFile)
0chain-core-sdk [INFO]   2023/05/26 10:19:47.137405 transaction_base.go:139: ******* Wallet SDK Version:v1.8.13-45-g29b9769 ******* (InitZCNSDK)
0chain-core-sdk [INFO]   2023/05/26 10:19:47.141720 wallet_base.go:413: https://dev1.zus.network/miner01/v1/client/put
0chain-core-sdk [INFO]   2023/05/26 10:19:47.141808 wallet_base.go:413: https://dev2.zus.network/miner01/v1/client/put
0chain-core-sdk [INFO]   2023/05/26 10:19:47.141907 wallet_base.go:413: https://dev3.zus.network/miner01/v1/client/put
0chain-core-sdk [DEBUG]  2023/05/26 10:19:47.463133 wallet_base.go:436: https://dev1.zus.network/miner01/v1/client/putStatus: 404 Not Found
0chain-core-sdk [DEBUG]  2023/05/26 10:19:47.463225 wallet_base.go:442: {"code":"resource_not_found","error":"resource_not_found: can't retrieve resource"}
0chain-core-sdk [DEBUG]  2023/05/26 10:19:47.599182 wallet_base.go:436: https://dev3.zus.network/miner01/v1/client/putStatus: 404 Not Found
0chain-core-sdk [DEBUG]  2023/05/26 10:19:47.599307 wallet_base.go:442: {"code":"resource_not_found","error":"resource_not_found: can't retrieve resource"}
0chain-core-sdk [DEBUG]  2023/05/26 10:19:47.672688 wallet_base.go:436: https://dev2.zus.network/miner01/v1/client/putStatus: 404 Not Found
0chain-core-sdk [DEBUG]  2023/05/26 10:19:47.672774 wallet_base.go:442: {"code":"resource_not_found","error":"resource_not_found: can't retrieve resource"}
panic: sync: negative WaitGroup counter

goroutine 10 [running]:
sync.(*WaitGroup).Add(0x14000068d60?, 0x10376ca60?)
	/usr/local/go/src/sync/waitgroup.go:62 +0x10c
sync.(*WaitGroup).Done(0x10370bce8?)
	/usr/local/go/src/sync/waitgroup.go:87 +0x20
github.com/0chain/zwalletcli/cmd.(*ZCNStatus).OnWalletCreateComplete(0x140000a4a80?, 0x103846fc0?, {0x0?, 0x0?}, {0x14000024ac0?, 0x0?})
	/Users/manohar/0chain/zwalletcli/cmd/common.go:91 +0xb0
github.com/0chain/gosdk/zcncore.RecoverWallet.func1()
	/Users/manohar/go/pkg/mod/github.com/0chain/gosdk@v1.8.16-0.20230425081954-9c58546912bf/zcncore/wallet_base.go:503 +0xb4
created by github.com/0chain/gosdk/zcncore.RecoverWallet
	/Users/manohar/go/pkg/mod/github.com/0chain/gosdk@v1.8.16-0.20230425081954-9c58546912bf/zcncore/wallet_base.go:493 +0xac
```

**Comment by YarikRevich** [comment]
@boddumanohar The given issue is not present on the latest version of zwallet and gosdk using demo and dev networks

**Comment by boddumanohar** [comment]
issue not present in latest zwallet
